# Generated by Django 6.0.5 on 2026-05-09 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_repost_poll_totp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0, help_text='Unique users who saw this')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SavedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, default='🔖', max_length=10)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_visibil_5a979a_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='impressions_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='For scheduled posts', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('scheduled', 'Scheduled')], db_index=True, default='published', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='none', max_length=10),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', 'status', '-created_at'], name='posts_post_visibil_441dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'publish_at'], name='posts_post_status_603554_idx'),
        ),
        migrations.AddField(
            model_name='postanalytics',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='posts.post'),
        ),
        migrations.AddField(
            model_name='savedcollection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postsave',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='posts.savedcollection'),
        ),
        migrations.AlterUniqueTogether(
            name='postanalytics',
            unique_together={('post', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='savedcollection',
            unique_together={('owner', 'name')},
        ),
    ]
