# Generated by Django 6.0.5 on 2026-05-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_v3_security_analytics_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url_field',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
