# Generated by Django 5.1.15 on 2026-05-11 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_one_time_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['created_by'], name='chat_room_created_620718_idx'),
        ),
    ]
