# Generated by Django 6.0.5 on 2026-05-09 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ban_user', 'Banned User'), ('unban_user', 'Unbanned User'), ('delete_post', 'Deleted Post'), ('delete_message', 'Deleted Message'), ('delete_story', 'Deleted Story'), ('resolve_report', 'Resolved Report'), ('dismiss_report', 'Dismissed Report'), ('warn_user', 'Warned User'), ('force_logout', 'Force Logged Out User'), ('promote_admin', 'Promoted to Admin'), ('impersonate', 'Impersonated User')], max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('message', 'Message'), ('user', 'User'), ('story', 'Story'), ('room', 'Room')], max_length=10)),
                ('target_id', models.PositiveBigIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment / Bullying'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence or Threats'), ('misinformation', 'Misinformation'), ('adult_content', 'Inappropriate / Adult Content'), ('copyright', 'Copyright Violation'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('resolved_action', 'Resolved — Action Taken'), ('resolved_dismissed', 'Resolved — Dismissed')], default='pending', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('auto_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='reports_rep_status_7dd5e5_idx'), models.Index(fields=['target_type', 'target_id'], name='reports_rep_target__6b1f9a_idx'), models.Index(fields=['reporter'], name='reports_rep_reporte_101677_idx')],
            },
        ),
    ]
