# Generated by Django 6.0.5 on 2026-05-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ban_user', 'Banned User'), ('unban_user', 'Unbanned User'), ('verify_user', 'Verified User'), ('unverify_user', 'Removed Verification'), ('delete_post', 'Deleted Post'), ('delete_message', 'Deleted Message'), ('delete_story', 'Deleted Story'), ('resolve_report', 'Resolved Report'), ('dismiss_report', 'Dismissed Report'), ('warn_user', 'Warned User'), ('force_logout', 'Force Logged Out User'), ('promote_admin', 'Promoted to Admin'), ('impersonate', 'Impersonated User'), ('export_data', 'Exported User Data'), ('delete_account', 'Deleted Account'), ('flag_content', 'AI-Flagged Content')], max_length=20),
        ),
    ]
