# Generated by Django 6.0.5 on 2026-05-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('message', 'New Message'), ('mention', 'Mention'), ('group_invite', 'Group Invitation'), ('message_seen', 'Message Seen'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('new_follower', 'New Follower'), ('post_like', 'Post Liked'), ('post_comment', 'Post Commented'), ('story_reaction', 'Story Reaction'), ('system', 'System Announcement')], max_length=20),
        ),
    ]
